### PR TITLE
Fix certain nodes not being seen as replenishable, and tweak Artifact logic

### PR DESCRIPTION
**Pull request by MrCheeze**

### CODE REVIEW

**Review by Pronyo-Chan — APPROVED** [review]
Looks good to me

**Comment by MrCheeze** [comment]
After testing with this change one thing I noticed is that Merluvlee still directs you to Koopa Village, even if the logic requires you to trade the artifact in Dry Dry Desert. Seems hard to fix tough.

Also, it looked to me like Merluvlee was unable to give hints about where the Artifact is, that at least should be fixed.

**Comment by Pronyo-Chan** [comment]
> After testing with this change one thing I noticed is that Merluvlee still directs you to Koopa Village, even if the logic requires you to trade the artifact in Dry Dry Desert. Seems hard to fix tough.

Definitely sounds hard to fix, would need special hint handling just for Kolorado...

>Also, it looked to me like Merluvlee was unable to give hints about where the Artifact is, that at least should be fixed. But that's a separate point from this pull request.

The crystal berry and water stone are other key items that only give access to one check and they are currently not included in the item hints. I think that's intentional to counter the fact that the hints are random and we want to make sure they're mostly useful. Artifact should get the same treatment.

**Comment by icebound777** [comment]
lgtm

**Pull request merged**
